import type {
	DISCOVER_DATA_ENPOINTS_DEV,
	DISCOVER_SEARCH_ENPOINTS_DEV,
} from '../enums/discover-endpoint.dev.enum';
import type {
	DISCOVER_DATA_ENPOINTS,
	DISCOVER_SEARCH_ENPOINTS,
} from '../enums/discover-endpoint.enum';
import type {
	DISCOVER_DATA_ENPOINTS_PROD,
	DISCOVER_SEARCH_ENPOINTS_PROD,
} from '../enums/discover-endpoint.prod.enum';
import type {
	DISCOVER_DATA_ENPOINTS_QA,
	DISCOVER_SEARCH_ENPOINTS_QA,
} from '../enums/discover-endpoint.qa.enum';

export type DISCOVER_DATA_ENPOINT_TYPE = 'SERVICE';

export type DISCOVER_SEARCH_ENPOINT_TYPE = 'SEARCH';

export type DISCOVER_ENPOINT_TYPE = DISCOVER_DATA_ENPOINT_TYPE | DISCOVER_SEARCH_ENPOINT_TYPE;

export type DISCOVER_ENPOINTS = DISCOVER_DATA_ENPOINTS | DISCOVER_SEARCH_ENPOINTS;

export type DISCOVER_DATA_ENPOINT_CONFIG = {
	[key in DISCOVER_DATA_ENPOINT_TYPE]:
		| DISCOVER_DATA_ENPOINTS
		| DISCOVER_DATA_ENPOINTS_PROD
		| DISCOVER_DATA_ENPOINTS_DEV
		| DISCOVER_DATA_ENPOINTS_QA;
};

export type DISCOVER_SEARCH_ENPOINT_CONFIG = {
	[key in DISCOVER_SEARCH_ENPOINT_TYPE]:
		| DISCOVER_SEARCH_ENPOINTS
		| DISCOVER_SEARCH_ENPOINTS_PROD
		| DISCOVER_SEARCH_ENPOINTS_DEV
		| DISCOVER_SEARCH_ENPOINTS_QA;
};

export type DISCOVER_ENPOINT_CONFIG = DISCOVER_DATA_ENPOINT_CONFIG & DISCOVER_SEARCH_ENPOINT_CONFIG;
